### ISSUE TITLE
rx-placement issue

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [ligato/vpp-agent#1392]
When setting rx placements like this:

```
value:
        name: "TenGigabitEthernet3/0/0"
        type: "DPDK"
        enabled: true
        rx_placements:
          - queue: 0
            worker: 0
          - queue: 1
            worker: 2
          - queue: 2
            worker: 4
          - queue: 3
            worker: 6
```
it logs the error queue 0 redefined rx placement. while when I am trying to set do different workers same interface with same queue using vpp cli it let me do that without any problem
