### ISSUE TITLE
How to run FullResync when vpp crashes

### ISSUE THREAD

**Issue by DreamerKMP** [ligato/vpp-agent#1639]
Hi,

I wrote my plugin and agent according to your answer.
It worked fine, but there were some issues when the VPP process that was connected to my agent crashed.

If I don't set the value of the `retry-connect-count` variable in `govpp.conf`, my agent continues to print `time="2020-03-11T17:07:59+09:00" level=warning msg="connecting failed (attempt 2/3): dial unix /run/vpp/api.sock: connect: connection refused"
` like messages and waits for a new VPP process. However, even after a few seconds, a new VPP process is running, my agent does not detect the event that it is connected again.
When I analyze the source code, I guess it is probably related to the handling of `govpp.Failed` in the `handleVPPConnectionEvents()` function of the `govppmux` plugin.

```golang
func (p *Plugin) handleVPPConnectionEvents(ctx context.Context) {
...
// plugins/govppmux/plugin_impl_govppmux.go
} else if event.State == govpp.Failed || event.State == govpp.Disconnected {
	p.infoMu.Lock()
	p.vppInfo.Connected = false
	p.infoMu.Unlock()

	p.lastConnErr = errors.Errorf("VPP connection lost (event: %+v)", event)
	p.StatusCheck.ReportStateChange(p.PluginName, statuscheck.Error, p.lastConnErr)
```

```golang
// git.fd.io/govpp/core/connection.go
func (c *Connection) connectLoop(connChan chan ConnectionEvent) {
	var reconnectAttempts int

	// loop until connected
	for {
		if err := c.vppClient.WaitReady(); err != nil {
			log.Debugf("wait ready failed: %v", err)
		}
		if err := c.connectVPP(); err == nil {
			// signal connected event
			connChan <- ConnectionEvent{Timestamp: time.Now(), State: Connected}
			break
		} else if reconnectAttempts < c.maxAttempts {
			reconnectAttempts++
			log.Warnf("connecting failed (attempt %d/%d): %v", reconnectAttempts, c.maxAttempts, err)
			time.Sleep(c.recInterval)
		} else {
                        // !!!!!!!  This line  !!!!!!!!
			connChan <- ConnectionEvent{Timestamp: time.Now(), State: Failed, Error: err}
			return
		}
	}

	// we are now connected, continue with health check loop
	c.healthCheckLoop(connChan)
}
```

So I checked to detect the connection to the new vpp process if I filled in the `retry-connect-count` variable in the `govpp.conf` file with the appropriate value.
After that, my agent applied **FullResync** to the new VPP process. But it didn't apply the behavior I expected.

The following is the output log at the time.
```
+======================================================================================================================+
| #17 - NB Transaction                                                                                      FullResync |
+======================================================================================================================+
  * transaction arguments:
      - seqNum: 17
      - type: NB Transaction, Full Resync
      - values:
          - key: config/vpp/l2/v2/xconnect/loop10
            val: { receive_interface:"loop10" transmit_interface:"loop11"  }
          - key: config/vpp/nilb/v1/bucket/test
            val: { name:"test" service_interface:"loop0" lookup_table_size:7 is_auto_build:true interfaces:"loop1" interfaces:"loop2"  }
          - key: config/vpp/v2/interfaces/loop0
            val: { name:"loop0" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop1
            val: { name:"loop1" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop10
            val: { name:"loop10" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop11
            val: { name:"loop11" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop2
            val: { name:"loop2" type:SOFTWARE_LOOPBACK enabled:true  }
o----------------------------------------------------------------------------------------------------------------------o
  * executed operations (2020-03-11 17:08:07.388 +0900 KST -> 2020-03-11 17:08:07.416 +0900 KST, dur: 28ms):
      1. CREATE [WAS-MISSING]:
          - key: config/vpp/v2/interfaces/loop0
          - value: { name:"loop0" type:SOFTWARE_LOOPBACK enabled:true  } 
      2. CREATE [WAS-MISSING]:
          - key: config/vpp/v2/interfaces/loop1
          - value: { name:"loop1" type:SOFTWARE_LOOPBACK enabled:true  } 
      3. CREATE [WAS-MISSING]:
          - key: config/vpp/v2/interfaces/loop10
          - value: { name:"loop10" type:SOFTWARE_LOOPBACK enabled:true  } 
      4. CREATE [WAS-MISSING]:
          - key: config/vpp/v2/interfaces/loop11
          - value: { name:"loop11" type:SOFTWARE_LOOPBACK enabled:true  } 
      5. CREATE [WAS-MISSING]:
          - key: config/vpp/l2/v2/xconnect/loop10
          - value: { receive_interface:"loop10" transmit_interface:"loop11"  } 
      6. CREATE [WAS-MISSING]:
          - key: config/vpp/v2/interfaces/loop2
          - value: { name:"loop2" type:SOFTWARE_LOOPBACK enabled:true  } 
      7. CREATE [WAS-MISSING]:
          - key: config/vpp/nilb/v1/bucket/test
          - value: { name:"test" service_interface:"loop0" lookup_table_size:7 is_auto_build:true interfaces:"loop1" interfaces:"loop2"  } 
x----------------------------------------------------------------------------------------------------------------------x
| #17 - NB Transaction                                                                                     took 27.9ms |
x----------------------------------------------------------------------------------------------------------------------x
```

The output of the first **FullResync** was as follows. This result is what I expected.
```
+======================================================================================================================+
| #0 - NB Transaction                                                                                       FullResync |
+======================================================================================================================+
  * transaction arguments:
      - seqNum: 0
      - type: NB Transaction, Full Resync
      - values:
          - key: config/vpp/l2/v2/xconnect/UNTAGGED-loop4
            val: <NIL>
          - key: config/vpp/l2/v2/xconnect/UNTAGGED-loop5
            val: <NIL>
          - key: config/vpp/l2/v2/xconnect/loop10
            val: { receive_interface:"loop10" transmit_interface:"loop11"  }
          - key: config/vpp/nilb/v1/bucket/UNTAGGED-0
            val: <NIL>
          - key: config/vpp/nilb/v1/bucket/UNTAGGED-1
            val: <NIL>
          - key: config/vpp/nilb/v1/bucket/test
            val: { name:"test" service_interface:"loop0" lookup_table_size:7 is_auto_build:true interfaces:"loop1" interfaces:"loop2"  }
          - key: config/vpp/v2/interfaces/UNTAGGED-loop0
            val: <NIL>
          - key: config/vpp/v2/interfaces/UNTAGGED-loop1
            val: <NIL>
          - key: config/vpp/v2/interfaces/UNTAGGED-loop2
            val: <NIL>
          - key: config/vpp/v2/interfaces/UNTAGGED-loop3
            val: <NIL>
          - key: config/vpp/v2/interfaces/UNTAGGED-loop4
            val: <NIL>
          - key: config/vpp/v2/interfaces/UNTAGGED-loop5
            val: <NIL>
          - key: config/vpp/v2/interfaces/loop0
            val: { name:"loop0" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop1
            val: { name:"loop1" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop10
            val: { name:"loop10" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop11
            val: { name:"loop11" type:SOFTWARE_LOOPBACK enabled:true  }
          - key: config/vpp/v2/interfaces/loop2
            val: { name:"loop2" type:SOFTWARE_LOOPBACK enabled:true  }
o----------------------------------------------------------------------------------------------------------------------o
  * executed operations (2020-03-11 17:06:46.407 +0900 KST -> 2020-03-11 17:06:46.488 +0900 KST, dur: 81ms):
      1. DELETE [DISCOVERED]:
          - key: config/vpp/l2/v2/xconnect/UNTAGGED-loop4
          - value: { receive_interface:"UNTAGGED-loop4" transmit_interface:"UNTAGGED-loop5"  } 
      2. DELETE [DISCOVERED]:
          - key: config/vpp/l2/v2/xconnect/UNTAGGED-loop5
          - value: { receive_interface:"UNTAGGED-loop5" transmit_interface:"UNTAGGED-loop4"  } 
      3. DELETE [DISCOVERED]:
          - key: config/vpp/nilb/v1/bucket/UNTAGGED-0
          - value: { name:"UNTAGGED-0" lookup_table_size:65521 interfaces:"UNTAGGED-loop3" interfaces:"UNTAGGED-loop1" interfaces:"UNTAGGED-loop2"  } 
      4. DELETE [DISCOVERED]:
          - key: config/vpp/nilb/v1/bucket/UNTAGGED-1
          - value: { name:"UNTAGGED-1" lookup_table_size:7 is_auto_build:true interfaces:"UNTAGGED-loop3" interfaces:"UNTAGGED-loop1" interfaces:"UNTAGGED-loop2"  } 
      5. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop0
          - value: { name:"UNTAGGED-loop0" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:00"  } 
      6. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop1
          - value: { name:"UNTAGGED-loop1" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:01"  } 
      7. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop2
          - value: { name:"UNTAGGED-loop2" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:02"  } 
      8. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop3
          - value: { name:"UNTAGGED-loop3" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:03"  } 
      9. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop4
          - value: { name:"UNTAGGED-loop4" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:04"  } 
      10. DELETE [DISCOVERED]:
          - key: config/vpp/v2/interfaces/UNTAGGED-loop5
          - value: { name:"UNTAGGED-loop5" type:SOFTWARE_LOOPBACK enabled:true phys_address:"de:ad:00:00:00:05"  } 
      11. CREATE:
          - key: config/vpp/v2/interfaces/loop0
          - value: { name:"loop0" type:SOFTWARE_LOOPBACK enabled:true  } 
      12. CREATE:
          - key: config/vpp/v2/interfaces/loop1
          - value: { name:"loop1" type:SOFTWARE_LOOPBACK enabled:true  } 
      13. CREATE:
          - key: config/vpp/v2/interfaces/loop10
          - value: { name:"loop10" type:SOFTWARE_LOOPBACK enabled:true  } 
      14. CREATE:
          - key: config/vpp/v2/interfaces/loop11
          - value: { name:"loop11" type:SOFTWARE_LOOPBACK enabled:true  } 
      15. CREATE:
          - key: config/vpp/l2/v2/xconnect/loop10
          - value: { receive_interface:"loop10" transmit_interface:"loop11"  } 
      16. CREATE:
          - key: config/vpp/v2/interfaces/loop2
          - value: { name:"loop2" type:SOFTWARE_LOOPBACK enabled:true  } 
      17. CREATE:
          - key: config/vpp/nilb/v1/bucket/test
          - value: { name:"test" service_interface:"loop0" lookup_table_size:7 is_auto_build:true interfaces:"loop1" interfaces:"loop2"  } 
x----------------------------------------------------------------------------------------------------------------------x
| #0 - NB Transaction                                                                                      took 81.3ms |
x----------------------------------------------------------------------------------------------------------------------x
```

How can I apply **FullResync** to a new vpp process, like when I first ran `DoResync()` in my agent plugin's `AfterInit()`?

This is another issue.
In the source code of the **release/3.0.x** branch of the vpp-agent, there are vpp plugins whose import path points to `github.com/ligato/cn-infra/*`.
Therefore, when we write the source code based on the **master** branch, errors occur because the import paths are different from the previous branch.
