### ISSUE TITLE
How to watch remote redis for sync？

### ISSUE THREAD

**Issue by xujunjie-cover** [ligato/vpp-agent#1825]
redis.conf
```
# NodeConfig
db: 0
dial-timeout: 0
enable-query-on-slave: true
endpoint: 172.18.22.214:6379
#endpoint: 127.0.0.1:6379
password: ""
pool:
  busy-timeout: 0
  idle-check-frequency: 0
  idle-timeout: 0
  max-connections: 0
ead-timeout: 0
tls:
  ca-file: ""
  cert-file: ""
  enabled: false
  key-file: ""
  skip-verify: false
write-timeout: 0
```

when connect to local redis and endpoint ip set 127.0.0.1,watch is ok;
when connect to remote redis and endpoint ip set remote ip, watch is wrong, No reaction for agent。

If something wrong with config? Thanks
